var imgs = {};
imgs = {
	text: './assets/images/text.png',
	zhengji: './assets/images/zhengji-1.png',
	t1: './assets/images/t1-4.png',
	bg: './assets/images/bg.jpg',
	entry: './assets/images/entry.png',
	title: './assets/images/title-2.png',
	submitInfo: './assets/images/submit-info-1.png',
	line: './assets/images/line.png',
	result: './assets/images/result.jpg',
	share: './assets/images/share.jpg',
	formBg: './assets/images/form-bg.png',
	invite: './assets/images/invite.png',
	logo: './assets/images/logo.png',
	logo1: './assets/images/logo1.png',
	help: './assets/images/help.png',
	seal: './assets/images/seal.png',
	arrow: './assets/images/arrow.png',
	aw: './assets/images/aw.png',
	back: './assets/images/back.png',
	xc: './assets/images/xc.png',
	sm: './assets/images/sm.png',
	restart: './assets/images/restart.png',
	listtop: './assets/images/listtop.jpg',
}
export default imgs;