var imgs = {};
imgs = {
	text: './assets/images/text.png',
	zhengji: './assets/images/zhengji.png',
	t1: './assets/images/t1.png',
	t2: './assets/images/t2.png',
	t3: './assets/images/t3.png',
	t4: './assets/images/t4.png',
	bg: './assets/images/bg.jpg',
	entry: './assets/images/entry.png',
	title: './assets/images/title.png',
	submitInfo: './assets/images/submit-info.png',
	line: './assets/images/line.png',
	result: './assets/images/result.jpg',
	share: './assets/images/share.jpg',
	formBg: './assets/images/form-bg.png',
	invite: './assets/images/invite.png',
	logo: './assets/images/logo.png',
	logo1: './assets/images/logo1.png',
	help: './assets/images/help.png',
	seal: './assets/images/seal.png',
	arrow: './assets/images/arrow.png',
	aw: './assets/images/aw.png',
	back: './assets/images/back.png',
	restart: './assets/images/restart.png',
	listtop: './assets/images/listtop.jpg',
}
export default imgs;